name: 'Docker over SSH'
description: 'Setup connection to remote Docker Daemon through SSH'
inputs:
  host:
    description: 'Remote Docker host'
    required: true
  port:
    description: 'SSH port'
    required: true
    default: '22'
  user:
    description: 'SSH user'
    required: true
  key:
    description: 'Content of SSH private key'
    required: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        SSH_KEY: ${{ inputs.key }}
        SSH_PORT: ${{ inputs.port }}
        SSH_HOST: ${{ inputs.host }}
        SSH_USER: ${{ inputs.user }}
      run: |
        mkdir -p .ssh
        echo "$SSH_KEY" > .ssh/id_rsa
        touch ~/.ssh/known_hosts
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        touch ~/.ssh/config
        echo "Host $SSH_HOST" >> .ssh/config
        echo "    IdentityFile ~/.ssh/id_rsa" >> .ssh/config
        echo "    StrictHostKeyChecking no" >> .ssh/config
        echo "DOCKER_HOST=ssh://$SSH_USER@$SSH_HOST:$SSH_PORT" >> $GITHUB_ENV

    - shell: bash
      env:
        SSH_PORT: ${{ inputs.port }}
        SSH_HOST: ${{ inputs.host }}
        SSH_USER: ${{ inputs.user }}
      run: echo "ssh://$SSH_USER@$SSH_HOST:$SSH_PORT"
      id: docker-host
